# Generated by Django 4.0.2 on 2022-03-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Degree', models.CharField(max_length=50, null=True, verbose_name='Degree')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmploymentType', models.CharField(max_length=30, null=True, verbose_name='Employment Type')),
            ],
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_text', models.CharField(max_length=30, null=True)),
                ('total', models.IntegerField(null=True, verbose_name='Total')),
                ('higher_studies_text', models.CharField(max_length=30, null=True)),
                ('higher_studies', models.IntegerField(null=True, verbose_name='Higher Studies')),
                ('entreprenuers', models.IntegerField(null=True, verbose_name='Entreprenuers')),
                ('entreprenuer_text', models.CharField(max_length=30, null=True)),
                ('known_persons', models.IntegerField(null=True, verbose_name='Known Persons')),
                ('known_persons_text', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YearOfCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year1', models.CharField(max_length=20, null=True, verbose_name='Year 1')),
                ('year2', models.CharField(max_length=20, null=True, verbose_name='Year 2')),
            ],
        ),
    ]
