# Generated by Django 4.0.2 on 2022-03-21 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumniportal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overview',
            name='entreprenuer_text',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='entreprenuers',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='higher_studies',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='higher_studies_text',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='known_persons',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='known_persons_text',
        ),
    ]
