# Generated by Django 4.0.3 on 2022-03-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumniportal', '0002_remove_overview_entreprenuer_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('time', models.TimeField(null=True, verbose_name='Time')),
                ('venue', models.CharField(max_length=50, null=True, verbose_name='Venue')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('poster', models.ImageField(null=True, upload_to='Events/', verbose_name='Poster')),
            ],
        ),
    ]
