# Generated by Django 4.0.3 on 2022-03-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumniportal', '0003_events'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AddField(
            model_name='events',
            name='date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
    ]
